const mongoose = require("mongoose");

// Helper function to create schema fields from your spec
const createSchemaField = (fieldSpec) => {
  let type;
  let required = fieldSpec.requirement === "M";

  switch (fieldSpec.type) {
    case "A": // Alphanumeric
      type = String;
      break;
    case "N": // Numeric
      type = Number;
      break;
    case "D": // Date (YYYYMMDD)
      type = Date;
      break;
    default:
      type = String; // Default to string if type is unknown
  }

  const schemaField = { type: type };

  if (required) {
    schemaField.required = [true, `${fieldSpec.dataElement} is required.`];
  } else if (fieldSpec.requirement === "A") {
    // "If Applies" fields are not strictly required by default Mongoose schema,
    // but validation logic will handle their conditional requirement.
    schemaField.required = false;
  }

  // Add enum for possible values if applicable
  if (Array.isArray(fieldSpec.possibleValues)) {
    // For values like "A = Ambient", store just "A" in DB.
    // Use a regex to handle inconsistent spacing around the "=".
    const enumValues = fieldSpec.possibleValues.map((val) => {
      const parts = val.split(/\s*=\s*/); // Robust split
      return parts[0]; // Always take the first part as the code
    });
    schemaField.enum = enumValues;
  }

  return schemaField;
};

// Define the schema specification as you provided it,
// including `start` and `end` for parsing/formatting.
const finishedProductSchemaSpec = [
  {
    item: 1,
    dataElement: "Part Number",
    aliases: ["FG Part Number", "Finished Good SKU", "Item Number", "SKU"],
    type: "A",
    length: 30,
    position: "01-30",
    format: "X(30)",
    possibleValues: null,
    requirement: "M",
    description: "A user defined code for the Finished Good",
    start: 0,
    end: 29,
  },
  {
    item: 2,
    dataElement: "Description",
    aliases: ["Desc", "Item Description", "Product Description"],
    type: "A",
    length: 60,
    position: "31-90",
    format: "X(60)",
    possibleValues: null,
    requirement: "M",
    description: "Line item description",
    start: 30,
    end: 89,
  },
  {
    item: 3,
    dataElement: "Unit Weight Lb.",
    aliases: ["Weight", "Unit Weight", "Weight (LBS)"],
    type: "N",
    length: 17,
    position: "91-107",
    format: "9(08).9(08)",
    possibleValues: null,
    requirement: "M",
    description: "Line item weight in pounds (LBS)",
    start: 90,
    end: 106,
  },
  {
    item: 4,
    dataElement: "Dutiable Value (USD)",
    aliases: ["Value", "Dutiable Value", "Customs Value"],
    type: "N",
    length: 17,
    position: "108-124",
    format: "9(08).9(08)",
    possibleValues: null,
    requirement: "M",
    description: "The material cost of the line item",
    start: 107,
    end: 123,
  },
  {
    item: 5,
    dataElement: "Filler",
    aliases: [],
    type: "A",
    length: 17,
    position: "125-141",
    format: "X(17)",
    possibleValues: "Blank Spaces",
    requirement: "O",
    description: "Blank spaces",
    start: 124,
    end: 140,
  },
  {
    item: 6,
    dataElement: "Added Value (USD)",
    aliases: ["Added Value", "Value Add"],
    type: "N",
    length: 17,
    position: "142-158",
    format: "9(08).9(08)",
    possibleValues: null,
    requirement: "M",
    description: "The added value of the line item",
    start: 141,
    end: 157,
  },
  {
    item: 7,
    dataElement: "Unit of Measure",
    aliases: ["UOM", "Unit"],
    type: "A",
    length: 3,
    position: "159-161",
    format: "X(03)",
    possibleValues: "For valid code see UOM file",
    requirement: "M",
    description: "Unit of Measure",
    start: 158,
    end: 160,
  },
  {
    item: 8,
    dataElement: "Country of Origin",
    aliases: ["COO", "Origin"],
    type: "A",
    length: 2,
    position: "162-163",
    format: "X(02)",
    possibleValues: "See table of valid codes for countries of orgin",
    requirement: "M",
    description: "Line item Country of Origin",
    start: 161,
    end: 162,
  },
  {
    item: 9,
    dataElement: "USA Importation HTS Code",
    aliases: ["Import HTS","US IMP", "US IMP HTS Code", "HTS Import"],
    type: "A",
    length: 12,
    position: "164-175",
    format: "X(12)",
    possibleValues: null,
    requirement: "M",
    description: "US HTS Code for the item to be imported into the US",
    start: 163,
    end: 174,
  },
  {
    item: 10,
    dataElement: "USA Exportation Code",
    aliases: ["Export HTS","US EXP","US EXP HTS Code", "Schedule B", "HTS Export"],
    type: "A",
    length: 12,
    position: "176-187",
    format: "X(12)",
    possibleValues: null,
    requirement: "M",
    description: "US HTS Code for the item to be exported from the US",
    start: 175,
    end: 186,
  },
  {
    item: 11,
    dataElement: "FDA Product Code",
    aliases: ["FDA Code"],
    type: "A",
    length: 7,
    position: "188-194",
    format: "X(07)",
    possibleValues: "DISCLAM for products that do not require a Product Code",
    requirement: "A",
    description:
      "The Code identifies the specific product and must agree with the invoice description of the product.",
    start: 187,
    end: 193,
  },
  {
    item: 12,
    dataElement: "FDA Storage",
    aliases: ["Storage Condition"],
    type: "A",
    length: 1,
    position: "195-195",
    format: "X(01)",
    possibleValues: ["A = Ambient", "F = Frozen", "R = Refrigerated"],
    requirement: "A",
    description: "Is the FDA Cargo Storage Status",
    start: 194,
    end: 194,
  },
  {
    item: 13,
    dataElement: "FDA Country of Origin",
    aliases: ["FDA COO"],
    type: "A",
    length: 2,
    position: "196-197",
    format: "X(02)",
    possibleValues: null,
    requirement: "A",
    description: null,
    start: 195,
    end: 196,
  },
  {
    item: 14,
    dataElement: "FDA Marker",
    aliases: ["FDA Flag"],
    type: "A",
    length: 3,
    position: "198-200",
    format: "X(03)",
    possibleValues: ["FD1 = FDA may be required", "FD2 = FDA is required"],
    requirement: "A",
    description: null,
    start: 197,
    end: 199,
  },
  {
    item: 15,
    dataElement: "FDA Affirmation of Compliance Code 1",
    aliases: ["FDA AOC Code 1", "AOC Code 1"],
    type: "A",
    length: 3,
    position: "201-203",
    format: "X(03)",
    possibleValues: "PMN = Device Premarket Notification No.",
    requirement: "A",
    description: null,
    start: 200,
    end: 202,
  },
  {
    item: 16,
    dataElement: "FDA Affirmation of Compliance Qualifier 1",
    aliases: ["FDA AOC Qualifier 1", "AOC Qualifier 1"],
    type: "A",
    length: 25,
    position: "204-228",
    format: "X(25)",
    possibleValues: null,
    requirement: "A",
    description: null,
    start: 203,
    end: 227,
  },
  {
    item: 17,
    dataElement: "FDA Affirmation of Compliance Code 2",
    aliases: ["FDA AOC Code 2", "AOC Code 2"],
    type: "A",
    length: 3,
    position: "229-231",
    format: "X(03)",
    possibleValues: "LST = Device Listing No.",
    requirement: "A",
    description: null,
    start: 228,
    end: 230,
  },
  {
    item: 18,
    dataElement: "FDA Affirmation of Compliance Qualifier 2",
    aliases: ["FDA AOC Qualifier 2", "AOC Qualifier 2"],
    type: "A",
    length: 25,
    position: "232-256",
    format: "X(25)",
    possibleValues: null,
    requirement: "A",
    description: null,
    start: 231,
    end: 255,
  },
  {
    item: 19,
    dataElement: "FDA Affirmation of Compliance Code 3",
    aliases: ["FDA AOC Code 3", "AOC Code 3"],
    type: "A",
    length: 3,
    position: "257-259",
    format: "X(03)",
    possibleValues: "DEV = Device Registration No.",
    requirement: "A",
    description: null,
    start: 256,
    end: 258,
  },
  {
    item: 20,
    dataElement: "FDA Affirmation of Compliance Qualifier 3",
    aliases: ["FDA AOC Qualifier 3", "AOC Qualifier 3"],
    type: "A",
    length: 25,
    position: "260-284",
    format: "X(25)",
    possibleValues: null,
    requirement: "A",
    description: null,
    start: 259,
    end: 283,
  },
  {
    item: 21,
    dataElement: "FDA Affirmation of Compliance Code 4",
    aliases: ["FDA AOC Code 4", "AOC Code 4"],
    type: "A",
    length: 3,
    position: "285-287",
    format: "X(03)",
    possibleValues: "Other FDA Code",
    requirement: "A",
    description: null,
    start: 284,
    end: 286,
  },
  {
    item: 22,
    dataElement: "FDA Affirmation of Compliance Qualifier 4",
    aliases: ["FDA AOC Qualifier 4", "AOC Qualifier 4"],
    type: "A",
    length: 25,
    position: "288-312",
    format: "X(25)",
    possibleValues: null,
    requirement: "A",
    description: null,
    start: 287,
    end: 311,
  },
  {
    item: 23,
    dataElement: "FDA Affirmation of Compliance Code 5",
    aliases: ["FDA AOC Code 5", "AOC Code 5"],
    type: "A",
    length: 3,
    position: "313-315",
    format: "X(03)",
    possibleValues: "Other FDA Code",
    requirement: "A",
    description: null,
    start: 312,
    end: 314,
  },
  {
    item: 24,
    dataElement: "FDA Affirmation of Compliance Qualifier 5",
    aliases: ["FDA AOC Qualifier 5", "AOC Qualifier 5"],
    type: "A",
    length: 25,
    position: "316-340",
    format: "X(25)",
    possibleValues: null,
    requirement: "A",
    description: null,
    start: 315,
    end: 339,
  },
  {
    item: 25,
    dataElement: "FDA Affirmation of Compliance Code 6",
    aliases: ["FDA AOC Code 6", "AOC Code 6"],
    type: "A",
    length: 3,
    position: "341-343",
    format: "X(03)",
    possibleValues: "Other FDA Code",
    requirement: "A",
    description: null,
    start: 340,
    end: 342,
  },
  {
    item: 26,
    dataElement: "FDA Affirmation of Compliance Qualifier 6",
    aliases: ["FDA AOC Qualifier 6", "AOC Qualifier 6"],
    type: "A",
    length: 25,
    position: "344-368",
    format: "X(25)",
    possibleValues: null,
    requirement: "A",
    description: null,
    start: 343,
    end: 367,
  },
  {
    item: 27,
    dataElement: "NAFTA",
    aliases: ["NAFTA Eligible"],
    type: "A",
    length: 1,
    position: "369-369",
    format: "X(1)",
    possibleValues: ["Y", "N"],
    requirement: "O",
    description: "The item does apply for NAFTA preference",
    start: 368,
    end: 368,
  },
  {
    item: 28,
    dataElement: "Preference Criterion",
    aliases: ["NAFTA Criterion"],
    type: "A",
    length: 1,
    position: "370-370",
    format: "X(1)",
    possibleValues: ["A", "B", "C", "D", "E", "F"],
    requirement: "O",
    description:
      "Preference Criterion. Mandatory when the item applies for NAFTA preference (Field 27 = Y)",
    start: 369,
    end: 369,
  },
  {
    item: 29,
    dataElement: "Producer",
    aliases: ["NAFTA Producer"],
    type: "A",
    length: 6,
    position: "371-376",
    format: "X(6)",
    possibleValues: ["Yes", "No (1)", "No (2)", "No (3)"],
    requirement: "O",
    description:
      "Producer. Mandatory when the item applies for NAFTA preference (Field 27 = Y)",
    start: 370,
    end: 375,
  },
  {
    item: 30,
    dataElement: "Net Cost",
    aliases: ["NAFTA Net Cost"],
    type: "A",
    length: 2,
    position: "377-378",
    format: "X(2)",
    possibleValues: ["CN", "NO"],
    requirement: "O",
    description:
      "Net Cost. Mandatory when the item applies for NAFTA preference (Field 27 = Y)",
    start: 376,
    end: 377,
  },
  {
    item: 31,
    dataElement: "Period (From)",
    aliases: ["NAFTA From", "Start Date"],
    type: "D",
    length: 10,
    position: "379-388",
    format: "YYYYMMDD",
    possibleValues: null,
    requirement: "O",
    description:
      "Start date of validity of certificate. Mandatory when the item applies for NAFTA preference (Field 27 = Y)",
    start: 378,
    end: 387,
  },
  {
    item: 32,
    dataElement: "Period (To)",
    aliases: ["NAFTA To", "End Date"],
    type: "D",
    length: 10,
    position: "389-398",
    format: "YYYYMMDD",
    possibleValues: null,
    requirement: "O",
    description:
      "Certificate expiration date. Mandatory when the item applies for NAFTA preference (Field 27 = Y)",
    start: 388,
    end: 397,
  },
  {
    item: 33,
    dataElement: "USML (ITAR)",
    aliases: ["USML", "ITAR"],
    type: "A",
    length: 20,
    position: "399-418",
    format: "X(20)",
    possibleValues: null,
    requirement: "A",
    description:
      "US Military License (When the material is classified for the US Gov as a Military good)",
    start: 398,
    end: 417,
  },
];

const finishedProductMongooseSchema = new mongoose.Schema({});
// Dynamically add fields to the Mongoose schema
finishedProductSchemaSpec.forEach((field) => {
  finishedProductMongooseSchema.add({
    [field.dataElement]: createSchemaField(field),
  });
});

// Add the schema specification as a static property for easy access
finishedProductMongooseSchema.statics.getSchemaSpec = () =>
  finishedProductSchemaSpec;

module.exports = mongoose.model(
  "FinishedProduct",
  finishedProductMongooseSchema
);